import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const homes = [
  {
    name: "Wall Eden Farm,Somerset",
    src: "/grant-durr-5xIMk4QMxb8-unsplash.jpg",
    range: {
      min: 2,
      max: 72,
    },
  },
  {
    name: "Port Owen Yacht Club, Port Owen",
    src: "/grant-durr-j2u0iw9UfO8-unsplash.jpg",
    range: {
      min: 2,
      max: 60,
    },
  },
  {
    name: "Noddfa, Gwynedd",
    src: "/travel-cents-WYLuNY5JG4E-unsplash.jpg",
    range: {
      min: 4,
      max: 32,
    },
  },
  {
    name: "Cortijo Estacada, Spain",
    src: "/sebastian-staines-6_8nhHo4fDc-unsplash.jpg",
    range: {
      min: 2,
      max: 8,
    },
  },
  {
    name: "Ridgeway House, Berkshire",
    src: "/grant-durr-8N6s3Fmw-h0-unsplash.jpg",
    range: {
      min: 2,
      max: 48,
    },
  },
  {
    name: "Vicarage Farm, Derbyshire",
    src: "/grant-durr-iSmv0eEcHHM-unsplash.jpg",
    range: {
      min: 8,
      max: 90,
    },
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Rustic Adventurers : Holiday House Group</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={`mx-auto h-screen flex flex-col ${inter.variable} font-sans`}>
        <nav className='border-b border-gray-200 py-5 relative z-20 bg-white shadow-[0_0_15px_0_rgb(0,0,0,0.1)]'>
          <div className='flex items-center lg:px-6 md:px-8 mx-auto max-w-7xl px-14'>
            <div className='flex flex-row items-center'>
              <a
                className='text-link hover:text-link-light transition-colors no-underline'
                href='/'>
                <span>
                  <svg height='26' viewBox='0 0 75 65' fill='#000'>
                    <title>Logo</title>
                    <path d='M37.59.25l36.95 64H.64l36.95-64z'></path>
                  </svg>
                </span>
              </a>
            </div>
            <div className='flex-1 justify-end hidden md:flex'>
              <nav className='flex-row inline-flex items-center'>
                <span className='ml-2 h-full flex items-center gap-4 cursor-not-allowed text-white'>
                  <a
                    data-variant='primary'
                    style={{
                      background:
                        "linear-gradient(45deg, rgba(255,214,0,1) 0%, rgba(255,122,0,1) 25%, rgba(255,0,105,1) 50%, rgba(211,0,197,1) 75%, rgba(118,56,250,1) 100%, rgba(255,214,0,1) 100%)",
                    }}
                    className='relative inline-flex items-center justify-evenly gap-3 pointer no-underline px-3.5 rounded-md font-medium outline-0 select-none align-middle whitespace-nowrap transition-colors ease-in duration-200 border border-solid text-white bg-success border-success-dark hover:bg-success/90 shadow-[0_5px_10px_rgb(0,68,255,0.12)] h-10 leading-10 text-[15px]'
                    href='https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fexamples%2Ftree%2Fmain%2Fedge-functions%2Fpower-parity-pricing&amp;project-name=edge-functions%2Fpower-parity-pricing&amp;repository-name=edge-functions%2Fpower-parity-pricing'
                    target='_blank'
                    rel='noreferrer'>
                    <Image
                      src={"/instagram-icon.png"}
                      alt='instagram icon'
                      width={"14"}
                      height='14'
                    />
                    <h1>Instagram</h1>
                  </a>
                </span>
              </nav>
            </div>
          </div>
        </nav>
        <div className='px-8 bg-white'>
          <div className='flex flex-col items-center justify-center py-10 bg-gray-50'>
            <div className='fixed h-full w-full inset-0 overflow-hidden opacity-75 bg-[#f8fafb]'>
              <Image
                className='absolute h-full w-full inset-0 object-cover text-transparent'
                src='/map.e9da4845.svg'
                alt='World Map'
                decoding='async'
                fill={true}
                loading={"lazy"}
              />
            </div>
            <main className='flex flex-col items-center flex-1 px-4 sm:px-20 text-center z-10 sm:pt-10 gap-6'>
              <div className='flex flex-col items-center flex-1'>
                <h1 className='text-3xl sm:text-5xl font-bold'>Coming Soon.</h1>
                <p className='mt-4 sm:text-xl text-lg text-gray-700'>
                  Browse through all our available houses.
                </p>
              </div>
              <div className='grid grid-cols-3 gap-8 items-center justify-center'>
                {homes.map(({ name, src, range: { min, max } }, i) => (
                  <div className='bg-white w-96 h-64 pb-4 flex flex-col gap-4 border border-gray-200 rounded-lg hover:shadow-md cursor-pointer'>
                    <div className='relative h-full w-full rounded-t-lg bg-black overflow-clip'>
                      <Image
                        className='object-cover'
                        src={`${src}`}
                        alt={`House Image ${i + 1}`}
                        loading={"lazy"}
                        fill={true}
                      />
                    </div>
                    <div className='px-4 flex flex-row items-baseline justify-between'>
                      <h1>{name}</h1>
                      <h4 className='flex flex-row items-center justify-evenly gap-2'>
                        <span>
                          <svg
                            xmlns='http://www.w3.org/2000/svg'
                            fill='none'
                            viewBox='0 0 24 24'
                            stroke-width='1.5'
                            stroke='currentColor'
                            className='w-4 h-4 stroke-gray-400'>
                            <path
                              stroke-linecap='round'
                              stroke-linejoin='round'
                              d='M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z'
                            />
                          </svg>
                        </span>
                        {`${min} - ${max}`}
                      </h4>
                    </div>
                  </div>
                ))}
              </div>
            </main>
          </div>
        </div>
        <footer className='py-10 w-full mt-auto border-t flex flex-row items-center justify-center bg-white z-20'>
          <span className='text-primary'>Created by</span>
          <a
            href='https://vercel.com'
            aria-label='Vercel.com Link'
            target='_blank'
            rel='noreferrer'
            className='text-black'>
            <h1 className='font-mono font-bold pl-2 pt-1'> adtjha</h1>
          </a>
        </footer>
      </div>
    </>
  );
}
